// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

/**
 * Standalone helpers that create OTel instrumentations, samplers, and metric
 * views.  These are used by the distro regardless of whether Azure Monitor is
 * enabled, so they must not depend on Azure Monitor handler classes.
 */

import type { RequestOptions } from "node:http";
import { createAzureSdkInstrumentation } from "@azure/opentelemetry-instrumentation-azure-sdk";
import { RateLimitedSampler } from "@azure/monitor-opentelemetry-exporter";
import type { Sampler } from "@opentelemetry/sdk-trace-base";
import type {
  HttpInstrumentationConfig,
  IgnoreOutgoingRequestFunction,
} from "@opentelemetry/instrumentation-http";
import { HttpInstrumentation } from "@opentelemetry/instrumentation-http";
import { MongoDBInstrumentation } from "@opentelemetry/instrumentation-mongodb";
import { MySQLInstrumentation } from "@opentelemetry/instrumentation-mysql";
import { PgInstrumentation } from "@opentelemetry/instrumentation-pg";
import { RedisInstrumentation } from "@opentelemetry/instrumentation-redis";
import { AzureFunctionsInstrumentation } from "@azure/functions-opentelemetry-instrumentation";
import { BunyanInstrumentation } from "@opentelemetry/instrumentation-bunyan";
import { WinstonInstrumentation } from "@opentelemetry/instrumentation-winston";
import type { Instrumentation } from "@opentelemetry/instrumentation";
import type { ViewOptions } from "@opentelemetry/sdk-metrics";

import type { InternalConfig } from "../shared/config.js";
import { ignoreOutgoingRequestHook } from "../azureMonitor/utils/common.js";
import { ApplicationInsightsSampler } from "../azureMonitor/traces/sampler.js";
import { logLevelToSeverityNumber } from "../azureMonitor/utils/logUtils.js";

// ── Instrumentations ────────────────────────────────────────────────

/**
 * Build the list of auto-instrumentations based on the distro configuration.
 * This covers trace instrumentations (HTTP, Azure SDK, DB clients, Azure
 * Functions) and log instrumentations (Bunyan, Winston).
 *
 * When `filterAzureMonitorRequests` is true the HTTP instrumentation will
 * suppress outgoing requests generated by the Azure Monitor exporter so they
 * don't appear as dependency telemetry.
 */
export function createInstrumentations(
  config: InternalConfig,
  options?: { filterAzureMonitorRequests?: boolean },
): Instrumentation[] {
  const instrumentations: Instrumentation[] = [];
  const filterAzureMonitor = options?.filterAzureMonitorRequests ?? false;

  // ── Trace instrumentations ──────────────────────────────────────
  if (config.instrumentationOptions.http?.enabled) {
    const httpConfig = config.instrumentationOptions.http as HttpInstrumentationConfig;

    if (filterAzureMonitor) {
      const providedHook = httpConfig.ignoreOutgoingRequestHook;
      const mergedHook: IgnoreOutgoingRequestFunction = (request: RequestOptions) => {
        const isAzureMonitorRequest = ignoreOutgoingRequestHook(request);
        if (!isAzureMonitorRequest && providedHook) {
          return providedHook(request);
        }
        return isAzureMonitorRequest;
      };
      httpConfig.ignoreOutgoingRequestHook = mergedHook;
    }

    instrumentations.push(new HttpInstrumentation(httpConfig));
  }

  if (config.instrumentationOptions.azureSdk?.enabled) {
    instrumentations.push(createAzureSdkInstrumentation(config.instrumentationOptions.azureSdk));
  }

  if (config.instrumentationOptions.mongoDb?.enabled) {
    instrumentations.push(new MongoDBInstrumentation(config.instrumentationOptions.mongoDb));
  }

  if (config.instrumentationOptions.mySql?.enabled) {
    instrumentations.push(new MySQLInstrumentation(config.instrumentationOptions.mySql));
  }

  if (config.instrumentationOptions.postgreSql?.enabled) {
    instrumentations.push(new PgInstrumentation(config.instrumentationOptions.postgreSql));
  }

  if (
    config.instrumentationOptions.redis?.enabled ||
    config.instrumentationOptions.redis4?.enabled
  ) {
    instrumentations.push(new RedisInstrumentation(config.instrumentationOptions.redis));
  }

  if (config.instrumentationOptions.azureFunctions?.enabled) {
    instrumentations.push(
      new AzureFunctionsInstrumentation(config.instrumentationOptions.azureFunctions),
    );
  }

  // ── Log instrumentations ────────────────────────────────────────
  const logLevelEnv = process.env.APPLICATIONINSIGHTS_INSTRUMENTATION_LOGGING_LEVEL;

  if (config.instrumentationOptions.bunyan?.enabled) {
    instrumentations.push(
      new BunyanInstrumentation({
        ...config.instrumentationOptions.bunyan,
        logSeverity: logLevelEnv ? logLevelToSeverityNumber(logLevelEnv) : undefined,
      }),
    );
  }

  if (config.instrumentationOptions.winston?.enabled) {
    instrumentations.push(
      new WinstonInstrumentation({
        ...config.instrumentationOptions.winston,
        logSeverity: logLevelEnv ? logLevelToSeverityNumber(logLevelEnv) : undefined,
      }),
    );
  }

  return instrumentations;
}

// ── Sampler ─────────────────────────────────────────────────────────

/**
 * Create an OTel sampler based on the distro configuration.
 *
 * Precedence:
 * 1. Explicit sampler provided via environment config (e.g. OTEL_TRACES_SAMPLER)
 * 2. Rate-limited sampler when `tracesPerSecond` > 0
 * 3. Percentage-based ApplicationInsightsSampler using `samplingRatio`
 */
export function createSampler(config: InternalConfig): Sampler {
  if (config.sampler) {
    return config.sampler;
  }
  if (config.tracesPerSecond && config.tracesPerSecond > 0) {
    return new RateLimitedSampler(config.tracesPerSecond);
  }
  return new ApplicationInsightsSampler(config.samplingRatio);
}

// ── Metric views ────────────────────────────────────────────────────

/**
 * Create metric views for the enabled instrumentations so that metric readers
 * have access to metrics produced by those instrumentations.
 */
export function createViews(config: InternalConfig): ViewOptions[] {
  const views: ViewOptions[] = [];

  if (config.instrumentationOptions.azureSdk?.enabled) {
    views.push({ meterName: "@azure/opentelemetry-instrumentation-azure-sdk" });
  }
  if (config.instrumentationOptions.http?.enabled) {
    views.push({ meterName: "@opentelemetry/instrumentation-http" });
  }
  if (config.instrumentationOptions.mongoDb?.enabled) {
    views.push({ meterName: "@opentelemetry/instrumentation-mongodb" });
  }
  if (config.instrumentationOptions.mySql?.enabled) {
    views.push({ meterName: "@opentelemetry/instrumentation-mysql" });
  }
  if (config.instrumentationOptions.postgreSql?.enabled) {
    views.push({ meterName: "@opentelemetry/instrumentation-pg" });
  }
  if (
    config.instrumentationOptions.redis?.enabled ||
    config.instrumentationOptions.redis4?.enabled
  ) {
    views.push({ meterName: "@opentelemetry/instrumentation-redis" });
  }

  return views;
}
